2024-05-09 12:33:43,743 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@hotmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username1', 'pbkdf2:sha256:600000$v6SEsJ9QtAtqQJNf$62928bfe8d18649ab22be16f0b43558be9f070bd6dfc00004e3da60e0e3a160d', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@hotmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 13:06:05,193 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@hotmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username1', 'pbkdf2:sha256:600000$4So9EXQZRXkK0JoU$02d42406ca7c3e39e0ccd2cc01dc03207456a7f805d41b2301edbca86b2e4592', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@hotmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 13:14:26,026 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username3', 'pbkdf2:sha256:600000$GrMhKD55vf2BhEV9$ddd56ed719c3122b64c6083fb585e0ae74ae6844866ad8155446e88a2a12779b', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 14:04:23,633 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username100', 'pbkdf2:sha256:600000$tFBqk8Fv31pf8eq1$b2fb59a75da21b7cb6980a648f9cbceba818ab2ff9b749803bfd4e0aec29b6de', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:118]
2024-05-09 14:26:44,447 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'rizkymirza18@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username101', 'pbkdf2:sha256:600000$ZX1vTWFAXX0aDl7u$567ca0776559e8db0ffadc52c42106471ad7a48cfe9ead9a043cb0fdf10d0c0e', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'rizkymirza18@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:27:04,290 ERROR: Failed to send email: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:117]
2024-05-09 14:27:04,291 ERROR: Exception occurred: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:27:31,528 ERROR: Failed to send email: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:117]
2024-05-09 14:27:31,529 ERROR: Exception occurred: (554, b'5.2.0 STOREDRV.Submission.Exception:OutboundSpamException; Failed to process message due to a permanent exception with message [BeginDiagnosticData]WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade. OutboundSpamException: WASCL UserAction verdict is not None. Actual verdict is RefuseQuota, ShowTierUpgrade.[EndDiagnosticData] [Hostname=TYZPR01MB5413.apcprd01.prod.exchangelabs.com]') [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:36:01,967 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'earthtoalvido@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username103', 'pbkdf2:sha256:600000$SoKuvcYwfQJZgY0K$b254adcae68116eebffa2ae8dac60854e21a26f333c63977de896a21e55637d9', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'earthtoalvido@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:36:10,458 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'earthtoalvd@gmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username103', 'pbkdf2:sha256:600000$PtJIhTQ87EPUA3hy$ead7e2dc199e152888c11cdf6c6db5235a60aef1e2c3ed373759730006f6f433', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'earthtoalvd@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-09 14:36:30,119 ERROR: Exception occurred: (MySQLdb.IntegrityError) (1062, "Duplicate entry 'alvidofaisal@hotmail.com' for key 'email'")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('test_username103', 'pbkdf2:sha256:600000$5TAl4i1miM162xx1$32df82fc8c4fd2c292b83317bb868fbf5768b82445a0b6f2dcc2368d9b05e900', 'First_Name', 'Last_Name', datetime.date(2000, 1, 1), 'alvidofaisal@hotmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/14/gkpj) [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:127]
2024-05-10 02:25:30,273 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:18:39,504 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:20:55,676 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:22:41,711 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:23:47,908 ERROR: Exception occurred: auth/templates/email_verification_template.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:24:23,276 ERROR: Exception occurred: features/auth/templates/email_verification.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:25:23,480 ERROR: Exception occurred: features/auth/templates/email_verification.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 15:25:52,168 ERROR: Exception occurred: templates/email_verification.html [in /home/ombah/revou-final-project-repositories/server/features/auth/routes.py:135]
2024-05-10 17:27:39,821 ERROR: Exception occurred: Install 'email_validator' for email validation support. [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:29:10,789 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('johnhalo', 'scrypt:32768:8:1$lop6eS80gq7kT0uq$9a4496d36b27625a5baea874b746c5252d93974a8072bcc1f78746e1937c43e3dfa47f9d9f7bc609d3a778a2192b6bfb22110ef5a75b3e2551765f63739efe0d', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:29:26,740 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('johnhalo', 'scrypt:32768:8:1$348Ppo77yF7oQyBL$4480baff8da8332fce1663ca2f69125d84c191ca3d6e89887b55173f9f0623c40c887667cc4b1979b71bb35bb9e2cf6a5094714232bd54a3160ce4a3ed84a15f', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:29:52,553 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('billy', 'scrypt:32768:8:1$VK6BxJfyQ2YsplJU$e9c2ff476b0e99cb5b1655a54b6c92f4a8d18e16b055531308797c56cb4d2d2607d500ac062cea007442b445d5fe3ff586bd0896d15958076f05c66e1e22c812', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:32:12,136 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('billy', 'scrypt:32768:8:1$jUMp2OqdjXxqh8p3$5ad08d8eb8efb9e4245a4ae71039c8c159fc69b6dba05c1e5d2f5f6c8751798f7c380295a3f7c46de5c128978982418299aaff3e7a8cb7b5edd1f8871761e1f1', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:32:35,520 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('billy', 'scrypt:32768:8:1$sikyjUfTf6hXesxh$5155a11ad21c7cfaae7ccb629d1d0ea2a8f0e1ebf5ddee87e90db5365cfcc7f6483475d4be941ead7fe6f5f03b764a84495681674c79714bb3e7d49636bbe466', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:36:56,952 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('billy', 'scrypt:32768:8:1$BHM63yVS7IsUz8iG$7c0d7ce0d2cdac77723b88fab24416070dcbd8b924460feb43e103d880a1b342c2007f9f9a3edc5acecf9f775d776a9c41d660e86f46b2d08023f37d967eead7', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:38:25,549 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('billy', 'scrypt:32768:8:1$qUAIE2fHmNysUGK3$2ab183197683247acf4ed83299abb0f94d1b5627e85bb5ee07db37bdcb6daa7a7ab40dd714c72fd4f165e7fc6374728bf74023bfaac22bcbc6536053920cb77c', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
2024-05-10 17:38:39,121 ERROR: Exception occurred: (MySQLdb.DataError) (1406, "Data too long for column 'password_hash' at row 1")
[SQL: INSERT INTO user (username, password_hash, first_name, last_name, birth_date, email, gender, confirmed) VALUES (%s, %s, %s, %s, %s, %s, %s, %s)]
[parameters: ('billy', 'scrypt:32768:8:1$6MD19K7fave0D35n$2998485877ddccb84fa6563b6962f937a03c7c36d2eb2eff28be1913b0b2d9e95a5cabf86eb035224f932d3e7667667714973ca2aa9310eef5f8ae5d0c171547', 'Dummy', 'Name', datetime.date(1999, 8, 16), 'bgus1708@gmail.com', 'MALE', 0)]
(Background on this error at: https://sqlalche.me/e/20/9h9h) [in D:\RevoU-Dir\final-project\file-2\revou-final-project-repositories\server\features\auth\routes.py:140]
